SELECT GIV_ITEM_DESC,STK_UNITS,STK_COST_PRICE,0 "Good",0 "Faulty",STK_QTY_STORE "Total Stock",stk_cost_price * stk_qty_store "Total Price",
(SELECT SUM(NVL(GIV_ISS_QTY,0)) FROM ECF_GOODS_ISSUE WHERE GIV_ITEM_DESC = outer.giv_item_desc AND TO_CHAR(GIV_DATE,'MM') = TO_CHAR(SYSDATE,'MM')-3) "Month 1",
(SELECT SUM(NVL(GIV_ISS_QTY,0)) FROM ECF_GOODS_ISSUE WHERE GIV_ITEM_DESC = outer.giv_item_desc AND TO_CHAR(GIV_DATE,'MM') = TO_CHAR(SYSDATE,'MM')-2) "Month 2",
(SELECT SUM(NVL(GIV_ISS_QTY,0)) FROM ECF_GOODS_ISSUE WHERE GIV_ITEM_DESC = outer.giv_item_desc AND TO_CHAR(GIV_DATE,'MM') = TO_CHAR(SYSDATE,'MM')-1) "Month 3",

NVL((SELECT SUM(NVL(GIV_ISS_QTY,0)) FROM ECF_GOODS_ISSUE WHERE GIV_ITEM_DESC = outer.giv_item_desc AND TO_CHAR(GIV_DATE,'MM') = TO_CHAR(SYSDATE,'MM')-3),0) +
NVL((SELECT SUM(NVL(GIV_ISS_QTY,0)) FROM ECF_GOODS_ISSUE WHERE GIV_ITEM_DESC = outer.giv_item_desc AND TO_CHAR(GIV_DATE,'MM') = TO_CHAR(SYSDATE,'MM')-2),0) +
NVL((SELECT SUM(NVL(GIV_ISS_QTY,0)) FROM ECF_GOODS_ISSUE WHERE GIV_ITEM_DESC = outer.giv_item_desc AND TO_CHAR(GIV_DATE,'MM') = TO_CHAR(SYSDATE,'MM')-1),0) "Toatl Stock Movement"

 FROM ECF_GOODS_ISSUE OUTER,ECF_STOCK_MASTER WHERE STK_ITEM_NAME = GIV_ITEM_DESC AND TRUNC(GIV_DATE) <= SYSDATE ORDER BY GIV_DATE DESC
